### ISSUE TITLE
unicode_support.h macOS build failure for faad2 2.8.7

### ISSUE THREAD

**Issue by ilovezfs** [knik0/faad2#6]
This seems to be a bug caused by https://github.com/knik0/faad2/pull/4

```
mp4read.c:27:10: fatal error: unicode_support.h: No such file or directory
 #include "unicode_support.h"
          ^~~~~~~~~~~~~~~~~~~
```

```
audio.c:41:10: fatal error: unicode_support.h: No such file or directory
 #include "unicode_support.h"
          ^~~~~~~~~~~~~~~~~~~
```

```
main.c:55:10: fatal error: unicode_support.h: No such file or directory
 #include "unicode_support.h"
          ^~~~~~~~~~~~~~~~~~~
```

And if I remove those includes, ultimately
```
libtool: link: /usr/local/bin/gcc-7 -Os -w -pipe -march=core2 -msse4 -mmacosx-version-min=10.11 -F/usr/local/Frameworks -Wl,-headerpad_max_install_names -o .libs/faad mp4read.o audio.o main.o  -L/usr/local/lib ../libfaad/.libs/libfaad.dylib -lm
Undefined symbols for architecture x86_64:
  "_faad_fopen", referenced from:
      _mp4read_open in mp4read.o
      _open_audio_file in audio.o
      _faad_main in main.o
```

Full log:
https://gist.github.com/ilovezfs/54bc87c0bbb5ee01ea2cafc138002e85

**Comment by knik0** [comment]
Probably fixed in 2.8.8, just released.

**Comment by ilovezfs** [comment]
Thanks @knik0! Yep it was fixed in 2.8.8
